*----------------------------------------------------------------------*
* Report generated by ABAP Report Wizard v. 1.0                        *
*----------------------------------------------------------------------*
* Report Name: Consumption Analisys Report                             *
* Created by: RRZ                                                      *
* Created on: 06/10/2009 at 11:54:52 CST                               *
*                                                                      *
* REVISION LOG                                                         *
*                                                                      *
* LOG SAP     DATE        AUTHOR       DESCRIPTION                     *
*----------------------------------------------------------------------*
* DEVK907403  11/23/09    Jeff Fromme  Add filtering options on report.
*                                      Also add "NB" PO creation option.
* DEVK907620  12/22/09    Bart Kraeger ABCDEF instead of ABC
*
* DEVK907671  12/22/09    Bart Kraeger Enhance "all ROP" selection to not
*                                      limit by days outstanding.
*                                      Correct safety stock selection text
*
* DEVK909330  5/16/12     jimmer       New Option AB "MIN" report
*
* DEVK909457  08/29/12    Prabha Mali  Add new report filters for ATP
*                                      check against ROP and Check Stock
*                                      at CDC.
*                                      Remove the AB "MIN" Report Check
*                                      Option, Minimum Days and Service
*                                      level parameters.
*
* DEVK909475 09/03/12     Prabha Mali  Added Min ROP in output, drill
*                                      down to MD04 & Branch Transfer.
* DEVK909484 09/07/12     Prabha Mali  Added XFR_QTY = ROP - ATP.
*                                      When Branch transfers created, the
*                                      XFR_QTY will be decremented.
*                                      Added button to delete records.
* DEVK909498 09/17/12     Prabha Mali  Made XFR_QTY hotspot and routing to
*                                      Branch Transfer. Show XFR_QTY 0 when
*                                      value is negative.
* DEVK909502 09/19/12     Prabha Mali  Removed XFR_QTY from hotspot and
*                                      made the column as editable.
*----------------------------------------------------------------------*

REPORT  zmm_consumption_rep.

* Begin of change DEVK909475
TYPE-POOLS : slis.
* End   of change DEVK909475

* Tables ( To support selection screen )
TABLES:
       makt,
       mara,
       marc,
       mkpf,
       tmabc. "Select option for ABC Indicator

*---------------------------------------------*
*      S E L E C T I O N   S C R E E N        *
*---------------------------------------------*

SELECTION-SCREEN: BEGIN OF BLOCK b01 WITH FRAME TITLE title01.
SELECT-OPTIONS: so_matnr                              FOR mara-matnr.
PARAMETERS: p_months(2) TYPE n DEFAULT 12.

SELECTION-SCREEN: BEGIN OF BLOCK b02 WITH FRAME TITLE title02.
SELECT-OPTIONS: so_werks                              FOR marc-werks.
SELECT-OPTIONS: so_lgort                              FOR marc-lgort.
SELECT-OPTIONS: so_matkl                              FOR mara-matkl.
SELECT-OPTIONS: p_days FOR (num03) NO INTERVALS .

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(29) text-002.
PARAMETERS: p_rop  RADIOBUTTON GROUP r0
            DEFAULT 'X' USER-COMMAND ucomm.
SELECTION-SCREEN COMMENT 35(35) text-004.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(29) text-003.
PARAMETERS: p_all  RADIOBUTTON GROUP r0.
SELECTION-SCREEN COMMENT 35(35) text-005.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(29) text-003.
PARAMETERS: p_sfty RADIOBUTTON GROUP r0.
SELECTION-SCREEN COMMENT 35(35) text-006.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK b02.

SELECTION-SCREEN: BEGIN OF BLOCK b03 WITH FRAME TITLE gd_filtr.
SELECT-OPTIONS: so_ekgrp                              FOR marc-ekgrp.
*  SELECT-OPTIONS: SO_CLASS                              FOR MARC-MAABC.
SELECT-OPTIONS: so_dismm               FOR marc-dismm.

SELECT-OPTIONS: so_mmsta               FOR marc-mmsta,
                so_mstae               FOR mara-mstae.
*SELECTION-SCREEN ULINE /1(40).
*SELECTION-SCREEN SKIP.
*SELECTION-SCREEN COMMENT /1(20) text-001.
SELECTION-SCREEN: END OF BLOCK b03.
SELECTION-SCREEN: BEGIN OF BLOCK b03b WITH FRAME TITLE text-011.

*{ DEVK907620 Change input checkboxes to select option.
SELECT-OPTIONS so_class FOR tmabc-maabc DEFAULT 'A'.
PARAMETERS: p_core AS CHECKBOX.
* Begin of change DEVK909457
PARAMETERS: p_atp    AS CHECKBOX,
            p_stkcdc AS CHECKBOX.
* End   of change DEVK909457
SELECTION-SCREEN: END OF BLOCK b03b.
*PARAMETER:  p_CL_A   AS CHECKBOX DEFAULT 'X',
*            p_CL_B   AS CHECKBOX DEFAULT SPACE,
*            p_CL_C   AS CHECKBOX DEFAULT SPACE.

*PARAMETER:  p_ORDR   AS CHECKBOX DEFAULT 'X'.
*} DEVK907620


*SELECTION-SCREEN ULINE /1(40).


SELECTION-SCREEN: BEGIN OF BLOCK b04 WITH FRAME TITLE gd_opt.
PARAMETERS: p_rpt RADIOBUTTON GROUP r1
          DEFAULT 'X' USER-COMMAND ucomm.
PARAMETERS: p_po RADIOBUTTON GROUP r1.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 5.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_ropval.
PARAMETERS: p_ropval(3) TYPE n  DEFAULT 0.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 5.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_vendor.
PARAMETERS: p_vendor LIKE bapimepoheader-vendor DEFAULT '9000'.
SELECTION-SCREEN END OF LINE.
SELECT-OPTIONS: s_axfrm  FOR mara-matnr NO-DISPLAY.
SELECT-OPTIONS: s_axfrbr FOR marc-werks NO-DISPLAY.
SELECTION-SCREEN: END OF BLOCK b04.
SELECTION-SCREEN: END OF BLOCK b01.

*---------------------------------------------*
*       D A T A   D E C L A R A T I O N       *
*---------------------------------------------*

CLASS lcl_event_handler DEFINITION DEFERRED.

* Types
TYPES: BEGIN OF ty_target,
*      chkbx       type checkbox,
      matnr       TYPE mara-matnr,
      ersda       TYPE mara-ersda,
      matkl       TYPE mara-matkl,
      maktx       TYPE makt-maktx,
      werks       TYPE marc-werks,
*      msehi       type mara-meins,
      meins       TYPE mara-meins,
      mstae       TYPE mara-mstae,
      mmsta       TYPE marc-mmsta,
      maabc       TYPE marc-maabc,
      ekgrp       TYPE marc-ekgrp,
      dismm       TYPE marc-dismm,
      dispo       TYPE marc-dispo,
      plifz       TYPE marc-plifz,
      webaz       TYPE marc-webaz,
      perkz       TYPE marc-perkz,
      disls       TYPE marc-disls,
      eisbe       TYPE marc-eisbe,
      mabst       TYPE marc-mabst,
      minbe       TYPE marc-minbe,
      sobsl       TYPE marc-sobsl,
      month1     TYPE sverbtaba-vbwrt,
      month2      TYPE sverbtaba-vbwrt,
      month3      TYPE sverbtaba-vbwrt,
      month4      TYPE sverbtaba-vbwrt,
      month5      TYPE sverbtaba-vbwrt,
      month6      TYPE sverbtaba-vbwrt,
      month7      TYPE sverbtaba-vbwrt,
      month8      TYPE sverbtaba-vbwrt,
      month9      TYPE sverbtaba-vbwrt,
      month10     TYPE sverbtaba-vbwrt,
      month11     TYPE sverbtaba-vbwrt,
      month12     TYPE sverbtaba-vbwrt,
      totyear     TYPE ztotsm,
      min_rop     TYPE marc-minbe,
      atp         TYPE /its/atp,
      xfr_qty     TYPE marc-minbe,                          "DEVK909484
      onorder     TYPE zonorder,
      buy_qty     TYPE zbuy_qty,
      zconsday    TYPE zconsday,
      zqtyleft    TYPE zqtyleft,
      supplant    TYPE zsupplant,
      END OF ty_target.

* Log Message Internal table

TYPES: BEGIN OF t_log,
        status     TYPE symsgid,
        ponum      TYPE symsgid,
        message    TYPE bapi_msg,
        key        TYPE bapi_msg,
       END OF t_log.

"abmin
TYPES: BEGIN OF str_m,
  matnr   TYPE matnr,           " Material Number
  werks   TYPE werks_d,         " Branch
  mblnr   TYPE mblnr,           " Number of Material Document
  mjahr	  TYPE mjahr,           " Material Document Year
  budat   TYPE budat,           " Posting Date in the Document
  bwart   TYPE bwart,           " Movement Type (Inventory Management)
  menge   TYPE rescconsumption, " Consumption
  meins   TYPE meins,           " Base Unit of Measure
  shkzg   TYPE shkzg,           " Debit/Credit Indicator
  xauto	  TYPE xauto,           " Line item automatically created
  xblnr   TYPE xblnr,           " Delivery number reference from the movement type table
  vgbel   TYPE vgbel,           " Sales order number reference from delivery detail table (used to calculate hits)
  zbucket TYPE rescconsumption,
  zflag	  TYPE i,
END OF str_m.

* Begin of change DEVK909484
TYPES: BEGIN OF ty_memory,
  matnr TYPE matnr,
  posnr TYPE posnr,
  werkssource TYPE werks,
  bukrs TYPE bukrs,
  ekorg TYPE ekorg,
  ekgrp TYPE ekgrp,
  labst TYPE labst,
  werkstarget TYPE werks,
  END OF ty_memory.
DATA : gt_memory TYPE STANDARD TABLE OF ty_memory.
* End   of change DEVK909484

DATA: gt_m TYPE TABLE OF str_m,
      wa_m TYPE str_m,
      sdate TYPE sy-datum.

* Internal tables and work areas
DATA:
      it_data        TYPE TABLE OF ty_target,
      it_log         TYPE TABLE OF t_log,
      wa_data        LIKE LINE OF it_data,
      gv_title       TYPE lvc_title,
      r_alv_template TYPE REF TO zcl_bt_alv_template.

DATA: BEGIN OF zges_verb_tab OCCURS 10.
        INCLUDE STRUCTURE sverbtaba.
DATA: END OF zges_verb_tab.
DATA: BEGIN OF zung_verb_tab OCCURS 10.
        INCLUDE STRUCTURE sverbtaba.
DATA: END OF zung_verb_tab.
DATA:
gi_bapiwmdvsx  TYPE TABLE OF bapiwmdvs,
gwa_bapiwmdvsx TYPE          bapiwmdvs,
      gi_bapiwmdvex  TYPE TABLE OF bapiwmdve,
      gwa_bapiwmdvex TYPE          bapiwmdve.
DATA: zmrp_items  LIKE  bapi_mrp_items OCCURS 0 WITH HEADER LINE,
zmrp_ind_lines  LIKE  bapi_mrp_ind_lines OCCURS 0 WITH HEADER LINE,
zmrp_total_lines  LIKE  bapi_mrp_total_lines OCCURS 0 WITH HEADER LINE,
zextensionout LIKE  bapiparex OCCURS 0 WITH HEADER LINE,
zmrp_list  TYPE  bapi_mrp_list,
zmrp_control_param TYPE  bapi_mrp_control_param,
zmrp_stock_detail  TYPE  bapi_mrp_stock_detail,
zreturn  TYPE  bapiret2.

* BAPI Structres for BAPI_PO_CREATE1 process:

DATA : wa_pohdr LIKE bapimepoheader,
       wa_pohdr_hold LIKE bapimepoheader,
       wa_pohdrx LIKE bapimepoheaderx,
       tab_podlv LIKE STANDARD TABLE OF bapimeposchedule,
       ltab_podlv LIKE STANDARD TABLE OF bapimeposchedule,
       wa_podlv LIKE bapimeposchedule,
       tab_podlvx LIKE STANDARD TABLE OF bapimeposchedulx,
       wa_podlvx LIKE bapimeposchedulx,
       tab_bapiret2 LIKE STANDARD TABLE OF bapiret2,
       wa_bapiret2 LIKE bapiret2,
       tab_poitem LIKE STANDARD TABLE OF bapimepoitem,
       tab_poitem_hold LIKE STANDARD TABLE OF bapimepoitem,

       ltab_poitem LIKE STANDARD TABLE OF bapimepoitem,
       wa_poitem LIKE LINE OF tab_poitem,
       tab_poitemx LIKE STANDARD TABLE OF bapimepoitemx,
       wa_poitemx LIKE LINE OF tab_poitemx,

       tab_tmp_ret2 LIKE STANDARD TABLE OF bapiret2,
       wa_tmp_ret2 LIKE bapiret2,
       wa_test_run LIKE bapiflag-bapiflag.

DATA: wa_buy_qty TYPE p DECIMALS 0.

DATA : BEGIN OF t_log1 OCCURS 0,
        status     TYPE symsgid,
        ponum      TYPE symsgid,
        message    TYPE bapi_msg,
        key        TYPE bapi_msg,
       END OF t_log1.

DATA:   lv_ponum LIKE wa_pohdr-po_number,
        wa_po_item LIKE wa_poitem-po_item,
        gd_year(4)   TYPE c,
        gd_month(2)  TYPE c,
        gd_accum_bucket LIKE tfacs-mon01,
        gd_accum_days  TYPE p.

* Begin of change DEVK909457
CONSTANTS : c_x    TYPE xfeld   VALUE 'X',
            c_90   TYPE sobsl   VALUE '90',
            c_3001 TYPE werks_d VALUE '3001'.
* End   of change DEVK909457

*SELECT-OPTIONS: so_class  FOR marc-maabc NO-DISPLAY.

* Begin of change DEVK909475
DATA : gv_custom_contnr TYPE REF TO cl_gui_custom_container,
       gv_grid          TYPE REF TO cl_gui_alv_grid,
       gt_fcat TYPE STANDARD TABLE OF lvc_s_fcat,
       gs_variant  TYPE disvariant,
       gs_fieldcat TYPE lvc_s_fcat,
       gs_layout   TYPE lvc_s_layo,
       gt_index TYPE lvc_t_row,
       gs_index LIKE LINE OF gt_index,
       gt_row TYPE lvc_t_roid,
       gs_col_id TYPE lvc_s_col,
       gs_row_id TYPE lvc_s_row,
       gv_lines TYPE i,
       gv_index TYPE sy-tabix,
       gv_lvc_s_stbl TYPE lvc_s_stbl VALUE 'X '.            "DEVK909502
* End   of change DEVK909475


*---------------------------------------------*
*   CLASS lcl_event_handler DEFINITION        *
*---------------------------------------------*
CLASS lcl_event_handler DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS:
        on_double_click FOR EVENT double_click OF cl_salv_events_table
                        IMPORTING row column,
* Begin of change DEVK909475
* when hotspot clicked on grid
        on_hotspot_click FOR EVENT hotspot_click  OF cl_gui_alv_grid
                         IMPORTING e_row_id e_column_id,

* Handling ALV Grids toolbar buttons
      handle_user_command FOR EVENT user_command OF cl_gui_alv_grid
                          IMPORTING e_ucomm,

* ALV Toolbar
        handle_alv_toolbar FOR EVENT toolbar OF cl_gui_alv_grid
                           IMPORTING e_object,
* End  of change DEVK909475
* Begin of change DEVK909502
        handle_data_changed FOR EVENT data_changed OF cl_gui_alv_grid
                            IMPORTING er_data_changed.
* End   of change DEVK909502

ENDCLASS.                    "lcl_event_handler DEFINITION
*---------------------------------------------*
*   CLASS lcl_event_handler IMPLEMENTATION    *
*---------------------------------------------*
CLASS lcl_event_handler IMPLEMENTATION.

  METHOD on_double_click.
* Insert double click functionality here
  ENDMETHOD.                    "ondoubleclick

* Begin of change DEVK909475
* Hotspot click
  METHOD on_hotspot_click.
    CASE e_column_id.
      WHEN 'MATNR'.
        PERFORM drilldown_to_md04 USING e_row_id e_column_id.
      WHEN 'ATP' OR 'XFR_QTY'.                              "DEVK909498
        PERFORM drilldown_to_branch_trans USING e_row_id e_column_id.
    ENDCASE.
  ENDMETHOD.                    "on_hotspot_click

* Add a toolbar Button
  METHOD handle_alv_toolbar.
    PERFORM handle_alv_toolbar USING e_object . "e_interactive.
  ENDMETHOD.                    "handle_alv_toolbar

* Handler for Toolbar Button Click - ALV
  METHOD handle_user_command.
    PERFORM handle_user_command USING e_ucomm.
  ENDMETHOD.                    "handle_user_command

* End   of change DEVK909475
* Begin of change DEVK909502
  METHOD handle_data_changed.

* Refresh the table display.
    PERFORM refresh_alv_grid.

  ENDMETHOD.                    "handle_data_changed
* End   of change DEVK909502
ENDCLASS.                    "lcl_event_handler IMPLEMENTATION

INITIALIZATION.
  SELECT SINGLE MAX( ddtext ) FROM dd02t INTO title01 WHERE tabname    = 'MARA'
                                                        AND ddlanguage = sy-langu. "#EC *
  SELECT SINGLE MAX( ddtext ) FROM dd02t INTO title02 WHERE tabname    = 'MARC'
                                                        AND ddlanguage = sy-langu. "#EC *
  gd_filtr = 'Report Filter Options'.
  gd_opt   = 'Selection Options'.

  p_days-sign   = 'I'.
  p_days-option = 'LE'.
  p_days-low    = '1'.
  APPEND p_days.

  so_werks-sign   = 'I'.
  so_werks-option = 'NE'.
  so_werks-low    = '3023'.
  APPEND so_werks.


AT SELECTION-SCREEN ON BLOCK b01.

  IF p_months > 0.
    IF p_months > 24.
      SET CURSOR FIELD 'P_MONTHS'.
      MESSAGE e001(00) WITH 'Monthly History Must not be Greater than 24'.
    ENDIF.
  ENDIF.

AT SELECTION-SCREEN ON BLOCK b02.

  IF p_all = 'X'.       "INCLUDE ALL

  ELSE.
    IF p_days-low > 0.
      IF p_days-low > 99.
        SET CURSOR FIELD 'P_DAYS'.
        MESSAGE e001(00) WITH 'Days Must not be Greater than 99'.
      ENDIF.
    ENDIF.
  ENDIF.


AT SELECTION-SCREEN ON BLOCK b04.

  IF p_po = 'X'
    AND p_vendor IS INITIAL.

    SET CURSOR FIELD 'P_VENDOR'.

    MESSAGE e001(00) WITH 'Must Enter Vendor'.
  ENDIF.

*---------------------------------------------*
*       D A T A   S E L E C T I O N           *
*---------------------------------------------*
START-OF-SELECTION.
*{ DEVK907620 Change input checkboxes to select option.
*  IF p_cl_a = 'X'.
*    so_class-sign   = 'I'.
*    so_class-option = 'EQ'.
*    so_class-low    = 'A'.
*    APPEND so_class.
*  ENDIF.
*
*  IF p_cl_b  = 'X'.
*    so_class-sign   = 'I'.
*    so_class-option = 'EQ'.
*    so_class-low    = 'B'.
*    APPEND so_class.
*  ENDIF.
*
*  IF p_cl_c  = 'X'.
*    so_class-sign   = 'I'.
*    so_class-option = 'EQ'.
*    so_class-low    = 'C'.
*    APPEND so_class.
*  ENDIF.
*} DEVK907620 Change input checkboxes to select option.


  PERFORM do_select.
  PERFORM select_core.

** Produce report **

  DATA: it_data_idx  TYPE sy-tabix,
        it_data_temp  LIKE it_data,
        wa_year_months(3) TYPE p,
        p_months_ch(2) TYPE c,
        wa_year_months_flag(1) TYPE c.

  it_data_idx = 1.

  IF p_months = 0.
    p_months_ch = '12'.

  ELSE.
    p_months_ch = p_months.
  ENDIF.

  wa_year_months_flag = space.

* Begin of change DEVK909457
  PERFORM process_data.
* End   of comment DEVK909457

  it_data[] = it_data_temp[].

  "EXIT.

*    **  Check if PO creation or report **
  IF p_po = 'X'.             "Create NB PO from selection *
    IF it_data[] IS INITIAL.
      t_log1-status = 'NO PROCESS'.

      t_log1-message = 'No items met qualification for reorder'.
      APPEND t_log1.
      CLEAR t_log1.
      it_log[] = t_log1[].
    ELSE.
      PERFORM create_nb_po.
    ENDIF.

  ENDIF.

*&---------------------------------------------------------------------*
*&      Form  process_data1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM process_data.

* Begin of change DEVK909457
  DATA : lv_excl_flag TYPE xfeld,
         lwa_data_temp TYPE ty_target,
         lv_min_rop TYPE p DECIMALS 0,
         lv_index TYPE sy-tabix,
         lv_total_buy TYPE zbuy_qty,
         lv_old_mat TYPE matnr.
* End   of change DEVK909457

  LOOP AT it_data INTO wa_data.

    CALL FUNCTION 'CONSUMPTION_READ_FOR_MM'
      EXPORTING
        matnr        = wa_data-matnr
        werks        = wa_data-werks
        perkz        = 'M'
        periv        = p_months_ch
      TABLES
        ges_verb_tab = zges_verb_tab
        ung_verb_tab = zung_verb_tab
      EXCEPTIONS
        wrong_call   = 1
        not_found    = 2
        OTHERS       = 3.
    IF sy-subrc <> 0.
*        MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
*                WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ELSE.

      LOOP AT zges_verb_tab.
        CASE sy-tabix.
          WHEN 1.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month1 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month1 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 2.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month2 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month2 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 3.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month3 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month3 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 4.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month4 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month4 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 5.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month5 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month5 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 6.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month6 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month6 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 7.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month7 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month7 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 8.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month8 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month8 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 9.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month9 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month9 = zges_verb_tab-vbwrt.
            ENDIF.

          WHEN 10.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month10 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month10 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 11.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month11 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month11 = zges_verb_tab-vbwrt.
            ENDIF.
          WHEN 12.
            IF NOT zges_verb_tab-kovbw IS INITIAL.
              wa_data-month12 = zges_verb_tab-kovbw.
            ELSE.
              wa_data-month12 = zges_verb_tab-vbwrt.
            ENDIF.

        ENDCASE.

        IF sy-tabix BETWEEN 1 AND p_months.

          IF wa_year_months_flag = space.
            gd_year   = zges_verb_tab-ertag+0(4).
            gd_month  = zges_verb_tab-ertag+4(2).
            PERFORM determine-bus-days-in-month.

          ENDIF.

          IF NOT zges_verb_tab-kovbw IS INITIAL.
            wa_data-totyear =  wa_data-totyear + zges_verb_tab-kovbw.
          ELSE.
            wa_data-totyear =  wa_data-totyear + zges_verb_tab-vbwrt.
          ENDIF.
        ENDIF.
      ENDLOOP.

      wa_year_months_flag = 'X'.

    ENDIF.

    CALL FUNCTION 'BAPI_MATERIAL_AVAILABILITY'
      EXPORTING
        plant      = wa_data-werks
        material   = wa_data-matnr
        unit       = wa_data-meins
        check_rule = 'ZZ'
      TABLES
        wmdvsx     = gi_bapiwmdvsx
        wmdvex     = gi_bapiwmdvex.

    READ TABLE gi_bapiwmdvex INTO gwa_bapiwmdvex WITH KEY com_date = sy-datum.

* Begin of change DEVK909457
    IF sy-subrc = 0.
* Begin of change DEVK909475
      CLEAR : lv_excl_flag.
      PERFORM atp_ropmin_check USING    wa_data-matnr
                                        wa_data-werks
                                        wa_data-minbe
                                        gwa_bapiwmdvex-com_qty
                               CHANGING lv_excl_flag
                                        wa_data-min_rop.
      MOVE gwa_bapiwmdvex-com_qty TO wa_data-atp.
      wa_data-xfr_qty = wa_data-minbe - wa_data-atp.

* Begin of change DEVK909498
      IF wa_data-xfr_qty LT 0.
        wa_data-xfr_qty = 0.
      ENDIF.
* End   of change DEVK909498

      MODIFY it_data FROM wa_data TRANSPORTING min_rop atp xfr_qty.
* End   of change DEVK909475

* If ATP < ROP MIN flag checked?
      IF p_atp = 'X'.
* Find out whether the record needs to be excluded from report or not?
        IF lv_excl_flag = 'X'.
          CLEAR: wa_data.
          CONTINUE.
        ENDIF.
      ENDIF.
    ELSE.
      CLEAR gwa_bapiwmdvex.
    ENDIF.
* End   of change DEVK909457

    CALL FUNCTION 'BAPI_MATERIAL_STOCK_REQ_LIST'
      EXPORTING
        material          = wa_data-matnr
        plant             = wa_data-werks
        get_item_details  = 'X'
        get_ind_lines     = 'X'
        get_total_lines   = 'X'
      IMPORTING
        mrp_list          = zmrp_list
        mrp_control_param = zmrp_control_param
        mrp_stock_detail  = zmrp_stock_detail
        return            = zreturn
      TABLES
        mrp_items         = zmrp_items
        mrp_ind_lines     = zmrp_ind_lines
        mrp_total_lines   = zmrp_total_lines
        extensionout      = zextensionout.
    wa_data-onorder = zmrp_stock_detail-fixed_recpt.

    DATA: wa_use_qty TYPE marc-minbe.

    IF p_sfty = 'X'.                   "Use Safety stock in place of ROP.
      wa_use_qty  = wa_data-eisbe.        "safety stock
    ELSE.
      wa_use_qty = wa_data-minbe.          "use ROP
    ENDIF.


*   Moving ATP Quantity
    MOVE gwa_bapiwmdvex-com_qty TO wa_data-atp.
    LOOP AT zmrp_ind_lines WHERE mrp_element_ind EQ 'U1'.
      CONCATENATE wa_data-supplant '/' zmrp_ind_lines-plan_plant2 INTO wa_data-supplant.
    ENDLOOP.

    IF wa_data-totyear NE 0.
*      wa_data-zconsday = wa_data-totyear / 365.           'replaced with business days
      wa_data-zconsday = wa_data-totyear / wa_year_months.

      IF wa_data-zconsday < 0.
        wa_data-zconsday = 0.
      ENDIF.

      IF wa_data-atp NE 0.
        IF wa_data-zconsday <> 0.
*          wa_data-zqtyleft = ( wa_data-atp - wa_data-minbe ) / wa_data-zconsday.
          wa_data-zqtyleft = ( wa_data-atp - wa_use_qty ) / wa_data-zconsday.
        ELSE.
          wa_data-zqtyleft = 0.
        ENDIF.
      ENDIF.
    ENDIF.
    "08/2011 jimmer add buy qty to grid
    wa_data-buy_qty = ( wa_data-minbe + ( ( wa_data-mabst - wa_data-minbe ) )
      * ( p_ropval / 100 ) ) - ( wa_data-atp + wa_data-onorder ).

    IF p_all = 'X'.
**      clear p_days.
**      refresh p_days.

*      IF wa_data-zconsday <> 0.
**      AND wa_data-zqtyleft IN p_days.     "remove day outstanding check - include all
      INSERT wa_data INTO it_data_temp INDEX it_data_idx.
      it_data_idx = it_data_idx + 1.
*      ENDIF.

    ELSE.

      IF wa_data-zconsday <> 0
      AND wa_data-zqtyleft IN p_days.
        IF wa_use_qty <> 0.

*          IF P_ORDR = 'X'.
*            if wa_data-onorder = 0.
          INSERT wa_data INTO it_data_temp INDEX it_data_idx.
          it_data_idx = it_data_idx + 1.

        ENDIF.
*        endif.
      ENDIF.
    ENDIF.

  ENDLOOP.

* Begin of change DEVK909457
* Filter the report output if the Check stock @ CDC checked
  IF p_stkcdc = c_x.
    SORT it_data_temp BY matnr.
* If the special procurement of material is '90', check the total buy qty of the material
* with the material ATP at CDC.
    LOOP AT it_data_temp INTO lwa_data_temp WHERE sobsl = c_90.  " procured from CDC
      IF lwa_data_temp-matnr NE lv_old_mat.
        CLEAR : wa_data.
        READ TABLE it_data INTO wa_data WITH KEY matnr = lwa_data_temp-matnr.
        IF sy-subrc = 0.
          CLEAR : lv_index.
          lv_index = sy-tabix.
          LOOP AT it_data INTO wa_data FROM lv_index
                                       WHERE matnr EQ lwa_data_temp-matnr
                                       AND   werks NE c_3001
                                       AND   sobsl EQ c_90.
* Fetch the Min ROP from zmm_mat_branch table updated by ROP calc program
            SELECT SINGLE min_rop INTO lv_min_rop
                                  FROM zmm_mat_branch
                                  WHERE matnr EQ wa_data-matnr
                                  AND   werks EQ wa_data-werks.
            IF sy-subrc = 0.
              IF wa_data-atp GE wa_data-minbe.
                " Do nothing!
              ELSEIF wa_data-atp GT lv_min_rop.
                lv_total_buy = lv_total_buy + wa_data-mabst - wa_data-atp.
              ELSEIF wa_data-atp LE lv_min_rop.
                lv_total_buy = lv_total_buy + wa_data-mabst - wa_data-atp.
              ENDIF.
            ENDIF.
            CLEAR : lv_min_rop.
          ENDLOOP.
        ENDIF.
* Check whether the material ATP at CDC is greater than the total qty buy of material at branches
        CLEAR : wa_data.
        READ TABLE it_data INTO wa_data WITH KEY matnr = lwa_data_temp-matnr
                                                 werks = c_3001.
        IF sy-subrc = 0.
          IF wa_data-atp GT lv_total_buy.
            DELETE it_data_temp WHERE matnr EQ lwa_data_temp-matnr
                                AND   sobsl EQ c_90.
          ENDIF.
        ELSE.  " If the Material at CDC is not in the selected data
* Get the ATP qty at CDC for the material
          CALL FUNCTION 'BAPI_MATERIAL_AVAILABILITY'
            EXPORTING
              plant      = c_3001
              material   = lwa_data_temp-matnr
              unit       = lwa_data_temp-meins
              check_rule = 'ZZ'
            TABLES
              wmdvsx     = gi_bapiwmdvsx
              wmdvex     = gi_bapiwmdvex.
          CLEAR : gwa_bapiwmdvex.
          READ TABLE gi_bapiwmdvex INTO gwa_bapiwmdvex WITH KEY com_date = sy-datum.
          IF sy-subrc = 0.
            IF gwa_bapiwmdvex-com_qty GT lv_total_buy.
              DELETE it_data_temp WHERE matnr EQ lwa_data_temp-matnr
                                  AND   sobsl EQ c_90.
            ENDIF.
          ENDIF.
        ENDIF.
        lv_old_mat = lwa_data_temp-matnr.
        CLEAR : lv_total_buy.
      ENDIF.
    ENDLOOP.
  ENDIF.
* End   of change DEVK909457

ENDFORM.                    "process_data

*&---------------------------------------------------------------------*
*&      Form  get_dates
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM get_dates.

  DATA: p_month LIKE t5a4a-dlymo.

  p_month = p_months_ch.

  CALL FUNCTION 'RP_CALC_DATE_IN_INTERVAL'
    EXPORTING
      date      = sy-datum
      days      = 0
      months    = p_month
      signum    = '-'
      years     = 0
    IMPORTING
      calc_date = sdate.

ENDFORM.                    "get_dates

*&---------------------------------------------------------------------*
*&      Form  get_movements
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_DATA     text
*      -->PT_M       text
*----------------------------------------------------------------------*
FORM get_movements
        USING    pt_s   LIKE it_data
                 p_data TYPE ty_target
        CHANGING pt_m   LIKE gt_m.

  DATA:  i_tmp TYPE TABLE OF ty_target.

  FIELD-SYMBOLS <s_work> TYPE ty_target.

  CLEAR: pt_m.
  REFRESH: pt_m, s_axfrbr.

  IF p_data-werks = '3001'.
    LOOP AT pt_s ASSIGNING <s_work>
      WHERE matnr = p_data-matnr
      AND sobsl = 90.

      s_axfrbr-sign   = 'I'.
      s_axfrbr-option = 'EQ'.
      s_axfrbr-low    = <s_work>-werks.
      s_axfrbr-high   = ' '.
      APPEND s_axfrbr.
    ENDLOOP.

    CHECK NOT s_axfrbr[] IS INITIAL.
    SELECT a~matnr " Material Number
           a~werks " Branch
           a~mblnr " Material Document
           b~mjahr " Material Year
           b~budat " Posting Date
           b~xblnr " Reference (Delivery Number)
           a~bwart " Goods Movement Type
           a~menge " Quantity
           a~meins " UOM
           a~shkzg " Debit/Credit Key
           a~xauto " STO Statistical Flag
         FROM mseg AS a
         JOIN mkpf AS b
           ON a~mblnr = b~mblnr   " Material Document Number
          AND a~mjahr = b~mjahr   " Material Document Year
         JOIN ekko AS c
           ON a~ebeln = c~ebeln   " Goods Receipt Purchase Orderd Number
         JOIN ekpo AS d
           ON a~ebeln = d~ebeln
          AND a~ebelp = d~ebelp
         APPENDING CORRESPONDING FIELDS OF TABLE pt_m
         WHERE a~matnr = p_data-matnr
           AND a~werks = p_data-werks
           AND a~bwart IN ('641','642')  " Sales order PGI and it's reversal.
           AND b~budat GE sdate AND
               b~budat LE sy-datum
           AND c~bsart IN ('EUB','UB')
           AND d~werks IN s_axfrbr.
  ELSE.
    SELECT a~matnr " Material Number
           a~werks " Branch
           a~mblnr " Material Document
           b~mjahr " Material Year
           b~budat " Posting Date
           b~xblnr " Reference (Delivery Number)
           a~bwart " Goods Movement Type
           a~menge " Quantity
           a~meins " UOM
           a~shkzg " Debit/Credit Key
           a~xauto " STO Statistical Flag
         FROM mseg AS a
         JOIN mkpf AS b
           ON a~mblnr = b~mblnr   " Material Document Number
          AND a~mjahr = b~mjahr   " Material Document Year
         APPENDING CORRESPONDING FIELDS OF TABLE pt_m
         WHERE a~matnr = p_data-matnr
           AND a~werks = p_data-werks
           AND a~bwart IN ('601','602')  " Sales order PGI and it's reversal.
           AND b~budat GE sdate AND
               b~budat LE sy-datum.
  ENDIF.



ENDFORM.                    "get_movements

*&---------------------------------------------------------------------*
*&      Form  set_sign_of_movement
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->PT_M       text
*----------------------------------------------------------------------*
FORM set_sign_of_movement CHANGING pt_m LIKE gt_m.
  FIELD-SYMBOLS: <m> TYPE str_m.

  LOOP AT pt_m ASSIGNING <m>.
    CASE <m>-shkzg.
      WHEN 'S'.
        MULTIPLY <m>-menge BY -1.
      WHEN 'H'.
    ENDCASE.
  ENDLOOP.
ENDFORM.                    "set_sign_of_movement

*&---------------------------------------------------------------------*
*&      Form  drop_reversals
*&---------------------------------------------------------------------*
*       Drop the reversal and the matching origional.
*----------------------------------------------------------------------*
FORM drop_reversals CHANGING pt_m LIKE gt_m.
  FIELD-SYMBOLS: <m>      TYPE str_m,
                 <m_work> TYPE str_m.

  SORT pt_m BY mblnr mjahr.    " Sort by doc number and year.

  LOOP AT pt_m ASSIGNING <m>.
    IF <m>-bwart = '602' OR <m>-bwart = '642' .
      CLEAR mkpf.

*     ***  FIND THE HEADER REC OF THE ORIGIONAL ***
      SELECT SINGLE a~mblnr a~mjahr       " doc number and year of the document that was reversed.
             INTO (mkpf-mblnr,mkpf-mjahr)
             FROM mkpf AS a
             JOIN mseg AS b
             ON   a~mblnr = b~smbln AND   " Head doc joined ON detail reference doc number
                  a~mjahr = b~sjahr       " Head doc joined ON detail reference doc year
             WHERE b~mblnr = <m>-mblnr    " Detail doc  = output doc number
               AND b~mjahr = <m>-mjahr    " Detail year = output doc year
               AND b~matnr = <m>-matnr    " Detail matl = output matl
               AND NOT b~smbln = space.   " Reference not = space.

*     *** MARK THE MATCHING ORIGIONAL FOR DELETION ***
      LOOP AT pt_m ASSIGNING <m_work> WHERE mblnr = mkpf-mblnr AND mjahr = mkpf-mjahr.
        <m_work>-zflag = 1.
      ENDLOOP.

*     *** ALSO MARK THE REVERSAL FOR DELETION ***
      <m>-zflag = 1.
    ENDIF.
  ENDLOOP.

  DELETE pt_m WHERE zflag = 1.
ENDFORM.                    "drop_reversals

*&---------------------------------------------------------------------*
*&      Form  combine_sales_orders
*&---------------------------------------------------------------------*
*       Combine movements for the same sales order number into one hit.
*----------------------------------------------------------------------*
FORM combine_sales_orders CHANGING pt_m LIKE gt_m.
  DATA: l_i          TYPE i.
  DATA: l_last_vgbel TYPE vgbel.

  FIELD-SYMBOLS: <m>      TYPE str_m,
                 <m_work> TYPE str_m.

  """ READ THE MATCHING SALES ORDER NUMBER. NOTE THAT THIS CODE WORKS """
  """ FOR STO DELIVERIES ALSO (IT RETURNS THE STO NUMBER).  I ALREADY """
  """ KNOW THE STO NUMBER FROM MY MATERIAL MOVEMENT SELECT STATEMENT  """
  """ SO I COULD DO SOMETHING WITH THAT TO MAKE THE PROGRAM FASTER    """
  """ IF PERFORMANCE PROGLEMS COME UP.                                """
  LOOP AT pt_m ASSIGNING <m>.
    SELECT SINGLE vgbel FROM lips INTO <m>-vgbel WHERE vbeln = <m>-xblnr.
  ENDLOOP.

  SORT pt_m BY vgbel budat.   " Sort by sales order number and date.

  LOOP AT pt_m ASSIGNING <m>.
    IF sy-tabix > 1.
      IF <m>-vgbel = l_last_vgbel.
        READ TABLE pt_m INDEX l_i ASSIGNING <m_work>.
        IF sy-subrc = 0.
          <m_work>-menge = <m_work>-menge + <m>-menge.
          <m>-zflag = 1.
        ENDIF.
      ELSE.
        l_i = sy-tabix.
        l_last_vgbel = <m>-vgbel.
      ENDIF.
    ELSE.
      l_i = 1.
      l_last_vgbel = <m>-vgbel.
    ENDIF.
  ENDLOOP.

  DELETE pt_m WHERE zflag = 1.
ENDFORM.                  "select_Data

*&---------------------------------------------------------------------*
*&      Form  do_select
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM do_select.

  SELECT a~matnr a~ersda a~matkl a~mstae b~maktx c~werks a~meins c~mmsta c~maabc c~ekgrp c~dismm
       c~dispo c~plifz c~webaz c~perkz c~disls c~eisbe c~mabst c~minbe c~sobsl
  FROM ( ( mara AS a
           INNER JOIN makt AS b ON a~matnr = b~matnr )
           INNER JOIN marc AS c ON b~matnr = c~matnr )
  INTO CORRESPONDING FIELDS OF TABLE it_data   " <--  Attention ! Field sequence !
  WHERE a~matnr IN so_matnr AND
        c~matnr IN so_matnr AND
        c~werks IN so_werks AND
        c~lgort IN so_lgort AND
        a~matkl IN so_matkl AND
        a~mstae IN so_mstae AND
        c~maabc IN so_class AND                  "limit class
        c~ekgrp IN so_ekgrp AND                  "limit purchase group
        c~dismm IN so_dismm AND                  "mrp type
        c~mmsta IN so_mmsta AND                  "plant-specific matl status
        a~mstae NE 'OB'.                         "do not select obsolete

*  SELECT a~matnr a~ersda a~matkl b~maktx c~werks a~meins c~mmsta c~maabc c~ekgrp c~dismm
*   c~dispo c~plifz c~webaz c~perkz c~disls c~eisbe c~mabst c~minbe
*    FROM ( ( marc AS c
*       INNER JOIN mara AS a ON a~matnr = c~matnr )
*       INNER JOIN makt AS b ON b~matnr = a~matnr )
*    INTO CORRESPONDING FIELDS OF TABLE it_data   " <--  Attention ! Field sequence !
*    WHERE
*    c~matnr IN so_matnr AND
*    c~ekgrp IN so_ekgrp AND
*    c~werks IN so_werks AND
*    c~lgort IN so_lgort AND
*    c~maabc IN so_class AND                  "limit class
*    c~dismm IN so_dismm AND                  "mrp type
*    c~mmsta IN so_mmsta AND
*    "a~matnr IN so_matnr AND
*    a~matkl IN so_matkl AND
*    a~mstae IN so_mstae AND
*    a~mstae NE 'OB'.                         "do not select obsolete

ENDFORM.                    "do_select
*&---------------------------------------------------------------------*
*&      Form  select_core
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM select_core.
  CHECK p_core = 'X'.

  "companywide core
  SELECT a~matnr a~ersda a~matkl a~mstae b~maktx c~werks a~meins c~mmsta c~maabc c~ekgrp c~dismm
     c~dispo c~plifz c~webaz c~perkz c~disls c~eisbe c~mabst c~minbe c~sobsl
    FROM ( ( mara AS a
         INNER JOIN makt AS b ON a~matnr = b~matnr )
         INNER JOIN marc AS c ON b~matnr = c~matnr )
    APPENDING CORRESPONDING FIELDS OF TABLE it_data   " <--  Attention ! Field sequence !
    WHERE a~matnr IN so_matnr AND
      c~matnr IN so_matnr AND
      c~werks IN so_werks AND
      c~lgort IN so_lgort AND
      a~matkl IN so_matkl AND
      a~mstae IN so_mstae AND
      "c~maabc IN so_class AND                  "limit class
      c~ekgrp IN so_ekgrp AND                  "limit purchase group
      c~dismm IN so_dismm AND                  "mrp type
      c~mmsta IN so_mmsta AND
      a~mstae EQ 'ZC'.                         "do not select obsolete

  SELECT a~matnr a~ersda a~matkl a~mstae b~maktx c~werks a~meins c~mmsta c~maabc c~ekgrp c~dismm
   c~dispo c~plifz c~webaz c~perkz c~disls c~eisbe c~mabst c~minbe
    FROM ( ( mara AS a
       INNER JOIN makt AS b ON a~matnr = b~matnr )
       INNER JOIN marc AS c ON b~matnr = c~matnr )
    APPENDING CORRESPONDING FIELDS OF TABLE it_data   " <--  Attention ! Field sequence !
    WHERE a~matnr IN so_matnr AND
    c~matnr IN so_matnr AND
    c~werks IN so_werks AND
    c~lgort IN so_lgort AND
    a~matkl IN so_matkl AND
    a~mstae IN so_mstae AND
    "c~maabc IN so_class AND                  "limit class
    c~ekgrp IN so_ekgrp AND                  "limit purchase group
    c~dismm IN so_dismm AND                  "mrp type
    c~mmsta EQ 'ZC'     AND                  "plant-specific matl status
    a~mstae NE 'OB'.                         "do not select obsolete

  SORT it_data BY matnr werks.
  DELETE ADJACENT DUPLICATES FROM it_data COMPARING matnr werks.

ENDFORM.                    "select_core

*&---------------------------------------------------------------------*
*&      Form  determine-business-days-in-month
*&---------------------------------------------------------------------*
*       Read factory calendar for needed month to accumulate working days
*       for use in determining quantity per day.
*----------------------------------------------------------------------*
FORM determine-bus-days-in-month.
  DATA:  wa_bus_month   TYPE tfacs,
         wa_month_accu  TYPE p.

  SELECT SINGLE * FROM tfacs
    INTO  wa_bus_month
    WHERE  ident = 'ZB'
    AND    jahr  = gd_year.

  IF sy-subrc = 0.

    CASE gd_month.

      WHEN '01'.
        gd_accum_bucket = wa_bus_month-mon01.

      WHEN '02'.
        gd_accum_bucket = wa_bus_month-mon02.

      WHEN '03'.
        gd_accum_bucket = wa_bus_month-mon03.

      WHEN '04'.
        gd_accum_bucket = wa_bus_month-mon04.

      WHEN '05'.
        gd_accum_bucket = wa_bus_month-mon05.

      WHEN '06'.
        gd_accum_bucket = wa_bus_month-mon06.

      WHEN '07'.
        gd_accum_bucket = wa_bus_month-mon07.

      WHEN '08'.
        gd_accum_bucket = wa_bus_month-mon08.

      WHEN '09'.
        gd_accum_bucket = wa_bus_month-mon09.

      WHEN '10'.
        gd_accum_bucket = wa_bus_month-mon10.

      WHEN '11'.
        gd_accum_bucket = wa_bus_month-mon11.

      WHEN '12'.
        gd_accum_bucket = wa_bus_month-mon12.

    ENDCASE.

    PERFORM loop_num_work_days.
    wa_year_months  = wa_year_months + gd_accum_days.
*    wa_data-totyear =  WA_data-totyear + GD_ACCUM_DAYS.

  ENDIF.

ENDFORM.                    "determine-business-days-in-month

*&---------------------------------------------------------------------*
*&      Form  LOOP_NUM_WORK_DAYS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM loop_num_work_days.
  DATA:  wa_idx TYPE p,
         wa_accum_day(1) TYPE c.

  gd_accum_days = 0.

  wa_idx = 1.
  DO 30 TIMES.

    IF gd_accum_bucket+wa_idx(1) = '1'.
      gd_accum_days = gd_accum_days + 1.
    ENDIF.

    ADD 1 TO wa_idx.

  ENDDO.


ENDFORM.                    "LOOP_NUM_WORK_DAYS
*&---------------------------------------------------------------------*
*&      Form  CREATE_NB_PO
*&---------------------------------------------------------------------*
*       Create NB PO for use in Load Builder (ZLB5) based on selected
*       items.
*----------------------------------------------------------------------*
FORM create_nb_po.

  DATA:  wa_parva  TYPE usr05-parva,
         wa_log_errors LIKE LINE OF tab_poitem.

*  get user's default purchasing group
  SELECT SINGLE parva
    INTO  wa_parva
    FROM  usr05
    WHERE  bname  = sy-uname
    AND    parid  = 'EKG'.

  IF sy-subrc = 0.
    wa_pohdr-pur_group  =  wa_parva.
  ELSE.
    wa_pohdr-pur_group  =  '340'.
  ENDIF.

**  set up header
  wa_pohdr-doc_type    = 'NB'.
  wa_pohdr-creat_date  = sy-datum.
  wa_pohdr-created_by  = sy-uname.
  wa_pohdr-vendor      = p_vendor.
  wa_pohdr-purch_org   = '3000'.

  wa_pohdrx-doc_type   = 'X'.
  wa_pohdrx-vendor     = 'X'.
  wa_pohdrx-purch_org  = 'X'.
  wa_pohdrx-pur_group  = 'X'.


** set up line items from IT_DATA

  wa_po_item = 0.

  LOOP AT it_data INTO wa_data.

*    if P_ROP = 'X'.

    IF p_ropval = 0.                    "use ROP quantity
      p_ropval = 100.
    ENDIF.

*       determine how much percent of EOQ to use in quantity calculation for line item
*       WA_BUY_QTY = ( ROP + ( ( MAX-STOCK - ROP ) / 100 ) * EOQ Percent ) - ( ATP + ON-ORDER ).

    wa_buy_qty = ( wa_data-minbe + ( ( wa_data-mabst - wa_data-minbe ) ) * ( p_ropval / 100 ) ) - ( wa_data-atp + wa_data-onorder ).
    wa_poitem-quantity = wa_buy_qty.

**      endif.

    IF wa_poitem-quantity <= 0.
      CONTINUE.
    ENDIF.

*    endif.

    wa_po_item = wa_po_item + 10.
    wa_poitem-po_item      =  wa_po_item.
    wa_poitem-material     =  wa_data-matnr.
    wa_poitem-plant        =  wa_data-werks.
**
    wa_poitem-net_price    =  '1.00'.
    wa_poitemx-po_item     =  wa_po_item.
    wa_poitemx-po_itemx    =  'X'.
    wa_poitemx-material    =  'X'.
    wa_poitemx-plant       =  'X'.
    wa_poitemx-quantity    =  'X'.
    wa_poitemx-net_price   =  'X'.

    APPEND wa_poitem TO tab_poitem.
    APPEND wa_poitemx TO tab_poitemx.

    CLEAR wa_poitem.
    CLEAR wa_poitemx.

  ENDLOOP.

  IF tab_poitem[] IS INITIAL.
    t_log1-status = 'NO PROCESS'.

    t_log1-message = 'No items met qualification for reorder'.
    APPEND t_log1.
    CLEAR t_log1.
    it_log[] = t_log1[].
  ELSE.
    PERFORM call_bapi_create_po.
  ENDIF.

ENDFORM.                    "CREATE_NB_PO


*&---------------------------------------------------------------------*
*&      Form  call_bapi_create_po
*&---------------------------------------------------------------------*
*       call funciton to create Purchase Order
*----------------------------------------------------------------------*
FORM call_bapi_create_po.

* BAPI to create the consolidated PO for the selected POs(Test Run).
* This is a test run so that if there is any error in creating or deleting
* the selected POs later the number range does not get incremented.
*  data:  wa_parva  type usr05-parva,
  DATA:  wa_log_errors LIKE LINE OF tab_poitem.


  wa_pohdr_hold     = wa_pohdr.
  tab_poitem_hold[] = tab_poitem[].

  CALL FUNCTION 'BAPI_PO_CREATE1'
    EXPORTING
      poheader  = wa_pohdr
      poheaderx = wa_pohdrx
      testrun   = 'X'
    TABLES
      return    = tab_bapiret2
      poitem    = tab_poitem
      poitemx   = tab_poitemx.

  IF sy-subrc EQ 0.
*     First read Error and Abort Message
    LOOP AT tab_bapiret2 INTO wa_bapiret2
                         WHERE type = 'E'
                          OR   type = 'A'.

      t_log1-status = 'ERROR'.

*      t_log1-field = wa_temp-ebeln.

      t_log1-message = wa_bapiret2-message.
      READ TABLE tab_poitem_hold INDEX wa_bapiret2-row INTO wa_log_errors.
      SHIFT wa_log_errors-material LEFT DELETING LEADING '0'.
      CONCATENATE 'Material' wa_log_errors-material 'PO Line' wa_log_errors-po_item INTO t_log1-key SEPARATED BY space.
      APPEND t_log1.
      CLEAR t_log1.

    ENDLOOP.

    READ TABLE tab_bapiret2 INTO wa_bapiret2 WITH KEY type = 'E' .  "number = 000.

  ENDIF.

  IF sy-subrc NE 0.

    REFRESH tab_bapiret2.
    CLEAR wa_bapiret2.
    CLEAR t_log1.
    REFRESH t_log1.

    IF p_vendor = '0000009000'.

      wa_pohdr  = wa_pohdr_hold.
      tab_poitem[] = tab_poitem_hold[].
    ENDIF.

* BAPI to create the consolidated PO for selected records (Original Run).
    CALL FUNCTION 'BAPI_PO_CREATE1'
      EXPORTING
        poheader         = wa_pohdr
        poheaderx        = wa_pohdrx
      IMPORTING
        exppurchaseorder = lv_ponum
      TABLES
        return           = tab_bapiret2
        poitem           = tab_poitem
        poitemx          = tab_poitemx.

    IF sy-subrc EQ 0.
*     First read Error and Abort Message

      LOOP AT tab_bapiret2 INTO wa_bapiret2
                           WHERE type = 'E'
                            OR   type = 'A'.

        t_log1-status = 'ERROR'.
        t_log1-message = wa_bapiret2-message.

        READ TABLE tab_poitem INDEX wa_bapiret2-row INTO wa_log_errors.
        SHIFT wa_log_errors-material LEFT DELETING LEADING '0'.
        CONCATENATE 'Material' wa_log_errors-material 'PO Line' wa_log_errors-po_item INTO t_log1-key SEPARATED BY space.
        APPEND t_log1.
        CLEAR t_log1.

      ENDLOOP.

      READ TABLE tab_bapiret2 INTO wa_bapiret2 WITH KEY type = 'E' .  "number = 000.

      IF sy-subrc <> 0.

*      *    Now Read Sucess Message
        CLEAR t_log1.
        LOOP AT tab_bapiret2 INTO wa_bapiret2
                             WHERE type = 'S'.

          t_log1-status = 'SUCCESS'.
          t_log1-message = wa_bapiret2-message.
          READ TABLE tab_poitem INDEX wa_bapiret2-row INTO wa_log_errors.
          SHIFT wa_log_errors-material LEFT DELETING LEADING '0'.
*          concatenate 'Material' wa_log_errors-material 'PO Line' wa_log_errors-po_item into t_log1-key separated by space.
          t_log1-ponum = lv_ponum.
          APPEND t_log1.
          CLEAR t_log1.

        ENDLOOP.

*       Commit the new PO.
        CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
          EXPORTING
            wait = 'X'.


      ENDIF.

      it_log[] = t_log1[].

    ENDIF.
  ELSE.
    it_log[] = t_log1[].
  ENDIF.

ENDFORM.                    "CREATE_NB_PO

*---------------------------------------------*
*        A L V   P R O C E S S I N G          *
*---------------------------------------------*
END-OF-SELECTION.
  DATA: wa_title(50)       TYPE c.

  IF p_po <> 'X'.             "Create NB PO from selection *
    gv_title = 'Butler AB Report'(tit).

* Begin of change DEVK909475
    IF sy-batch = 'X'.
* End   of change DEVK909475

*Build ALV Template Object
      zcl_bt_alv_template=>factory(
                     EXPORTING  im_syrepid = sy-repid
                                im_lheader = gv_title
                                im_allowls = abap_true         " Allow layout save
                     IMPORTING  ex_alvo    = r_alv_template
                     CHANGING   ch_datatab = it_data ).
* Handle events
      SET HANDLER lcl_event_handler=>on_double_click FOR r_alv_template->r_events.

* ALV Table Display
      r_alv_template->r_table->display( ).
* Begin of change DEVK909475
    ELSE.
      CALL SCREEN 0100.
    ENDIF.
* End   of change DEVK909475
  ELSE.
    IF lv_ponum IS INITIAL.
      lv_ponum = 'ERROR'.
    ENDIF.

    CONCATENATE  'BUTLER NB-PO Result:' lv_ponum INTO wa_title SEPARATED BY space.
    gv_title = wa_title.

*   Build ALV Template Object
    zcl_bt_alv_template=>factory(
                 EXPORTING  im_syrepid = sy-repid
                            im_lheader = gv_title
                            im_allowls = abap_false  " Allow layout save
                 IMPORTING  ex_alvo    = r_alv_template
                 CHANGING   ch_datatab = it_log ).
*   Handle events
    SET HANDLER lcl_event_handler=>on_double_click FOR r_alv_template->r_events.

*   ALV Table Display
    r_alv_template->r_table->display( ).


    IF  lv_ponum = 'ERROR'.
*Build ALV Template Object
      zcl_bt_alv_template=>factory(
                     EXPORTING  im_syrepid = sy-repid
                                im_lheader = gv_title
                                im_allowls = abap_false         " Allow layout save
                     IMPORTING  ex_alvo    = r_alv_template
                     CHANGING   ch_datatab = tab_poitem_hold ).
*    r_alv_template = .
* Handle events
      SET HANDLER lcl_event_handler=>on_double_click FOR r_alv_template->r_events.
* ALV Table Display
      r_alv_template->r_table->display( ).

    ELSE.
      SET PARAMETER ID: 'BES' FIELD lv_ponum.

    ENDIF.
  ENDIF.

* Handle events
*  set handler lcl_event_handler=>on_double_click for r_alv_template->r_events.
* ALV Table Display
*  r_alv_template->r_table->display( ).
*&---------------------------------------------------------------------*
*&      Form  ATP_ROPMIN_CHECK
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_WA_DATA_MINBE  text
*      -->P_GWA_BAPIWMDVEX_COM_QTY  text
*----------------------------------------------------------------------*
FORM atp_ropmin_check  USING    p_matnr TYPE matnr
                                p_werks TYPE werks_d
                                p_minbe TYPE minbe
                                p_atp_qty TYPE mng06
                       CHANGING p_excl_flag TYPE xfeld
                                p_min_rop   TYPE minbe.

  DATA : lv_min_rop TYPE p DECIMALS 0.

* Fetch the Min ROP value from ZMM_MAT_BRANCH
  SELECT SINGLE min_rop INTO lv_min_rop
                        FROM zmm_mat_branch
                        WHERE matnr EQ p_matnr
                        AND   werks EQ p_werks.

* Check if the ATP is >= ROP at branch
  IF p_atp_qty GE p_minbe.
    p_excl_flag = 'X'.
  ELSEIF p_atp_qty GT lv_min_rop.
    p_excl_flag = 'X'.
  ELSEIF p_atp_qty LE lv_min_rop.
    CLEAR : p_excl_flag.
  ENDIF.

  MOVE : lv_min_rop TO p_min_rop.

ENDFORM.                    " ATP_ROPMIN_CHECK
*&---------------------------------------------------------------------*
*&      Form  DRILLDOWN_TO_MD04
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_ROW  text
*      -->P_COLUMN  text
*----------------------------------------------------------------------*
FORM drilldown_to_md04  USING    p_row
                                 p_column.
  DATA : ls_data TYPE ty_target.

  READ TABLE it_data INTO ls_data INDEX p_row.
  SET PARAMETER ID 'MAT' FIELD ls_data-matnr.
  SET PARAMETER ID 'WRK' FIELD ls_data-werks.

  CALL TRANSACTION 'MD04' AND SKIP FIRST SCREEN.

ENDFORM.                    " DRILLDOWN_TO_MD04
*&---------------------------------------------------------------------*
*&      Form  DRILLDOWN_TO_BRANCH_TRANS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_ROW  text
*      -->P_COLUMN  text
*----------------------------------------------------------------------*
FORM drilldown_to_branch_trans  USING    p_row
                                         p_column.

* Begin of change DEVK909484
  CLEAR : gv_index.
  gv_index = p_row.
  FREE MEMORY ID 'ZABBRANCH'.
* End   of change DEVK909484

  READ TABLE it_data INTO wa_data INDEX p_row.
  SET PARAMETER ID 'MAT' FIELD wa_data-matnr.
  SET PARAMETER ID 'WRK' FIELD wa_data-werks.

  CALL TRANSACTION '/ITS/MM_BRANCH_TRANS' AND SKIP FIRST SCREEN.

* Begin of change DEVK909484
  PERFORM update_xfrqty_in_it_data.
  PERFORM refresh_alv_grid.
* End  of change DEVK909484

ENDFORM.                    " DRILLDOWN_TO_BRANCH_TRANS
*&---------------------------------------------------------------------*
*&      Form  SALV_USER_COMMAND
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM salv_user_command.

ENDFORM.                    "SALV_USER_COMMAND
*&---------------------------------------------------------------------*
*&      Module  STATUS_0100  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE status_0100 OUTPUT.
  SET PF-STATUS 'ZABRPT'.
  SET TITLEBAR 'TITLE'.

ENDMODULE.                 " STATUS_0100  OUTPUT
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0100  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE user_command_0100 INPUT.

* Begin of change DEVK909502
* Find the current row and column.
  CALL METHOD gv_grid->get_current_cell
    IMPORTING
      es_col_id = gs_col_id
      es_row_id = gs_row_id.
* End  of change DEVK909502

  CASE sy-ucomm.

    WHEN 'BACK'.
      LEAVE TO SCREEN 0.

    WHEN 'EXIT'.
      LEAVE TO SCREEN 0.

    WHEN 'CANC'.
      LEAVE TO SCREEN 0.

    WHEN '&SRL'.
      PERFORM stock_req.

    WHEN '&TRANS'.
      FREE MEMORY ID 'ZABBRANCH'.                           "DEVK909484
      PERFORM call_branch_transfer.

* Begin of change DEVK909484
    WHEN '&DELETE'.
      PERFORM delete_row_selected.
      PERFORM refresh_alv_grid.
* End   of change DEVK909484

  ENDCASE.

ENDMODULE.                 " USER_COMMAND_0100  INPUT
*&---------------------------------------------------------------------*
*&      Module  DISPLAY_ABREPORT  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE display_abreport OUTPUT.

  IF gv_custom_contnr IS INITIAL.                           "DEVK909484

    IF cl_gui_alv_grid=>offline( ) IS INITIAL.

* Create the custom container
      CREATE OBJECT gv_custom_contnr
        EXPORTING
          container_name              = 'CUST_CNTR'
        EXCEPTIONS
          cntl_error                  = 1
          cntl_system_error           = 2
          create_error                = 3
          lifetime_error              = 4
          lifetime_dynpro_dynpro_link = 5
          OTHERS                      = 6.

      IF sy-subrc <> 0.
        MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno
                   WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
      ENDIF.

      CLEAR : gs_layout.

* Set the alv grid layout
      gs_layout-smalltitle = space.  "Default Grid title to small font
      gs_layout-cwidth_opt = 'X'.
      gs_layout-grid_title = 'Butler AB Report'.
      gs_layout-sel_mode   = 'A'.
      gs_layout-zebra   = 'X'.
      gs_variant-report = sy-repid.

* Create alv grid
      CREATE OBJECT gv_grid
        EXPORTING
          i_parent          = gv_custom_contnr
        EXCEPTIONS
          error_cntl_create = 1
          error_cntl_init   = 2
          error_cntl_link   = 3
          error_dp_create   = 4
          OTHERS            = 5.

      IF sy-subrc <> 0.
        MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno
                   WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
      ENDIF.

* Build field catalog for display mode
      PERFORM prepare_fcat_disp.

* Modify field catalog
      PERFORM modify_field_cat.
      SET HANDLER lcl_event_handler=>handle_alv_toolbar FOR gv_grid.

* Display the report in the grid
      CALL METHOD gv_grid->set_table_for_first_display
        EXPORTING
          is_variant                    = gs_variant
          i_save                        = 'A'
          is_layout                     = gs_layout
          i_default                     = 'X'
        CHANGING
          it_fieldcatalog               = gt_fcat
          it_outtab                     = it_data
        EXCEPTIONS
          invalid_parameter_combination = 1
          program_error                 = 2
          too_many_lines                = 3
          OTHERS                        = 4.

      IF sy-subrc <> 0.
        MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno
                   WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
      ENDIF.

      SET HANDLER lcl_event_handler=>on_hotspot_click FOR gv_grid.
      SET HANDLER lcl_event_handler=>handle_user_command FOR gv_grid.

* Begin of change DEVK909502
      CALL METHOD gv_grid->register_edit_event
        EXPORTING
          i_event_id = cl_gui_alv_grid=>mc_evt_enter.

      SET HANDLER lcl_event_handler=>handle_data_changed FOR gv_grid.
* End  of change DEVK909502
    ENDIF.

* Begin of change DEVK909484
  ELSE.
    IF cl_gui_alv_grid=>offline( ) IS INITIAL.
      IF NOT gv_grid IS INITIAL.
        CALL METHOD gv_grid->refresh_table_display
          EXPORTING
            is_stable = gv_lvc_s_stbl
          EXCEPTIONS
            finished  = 1
            OTHERS    = 2.
      ENDIF.
    ENDIF.
  ENDIF.
* End   of change DEVK909484

ENDMODULE.                 " DISPLAY_ABREPORT  OUTPUT
*&---------------------------------------------------------------------*
*&      Form  PREPARE_FCAT_DISP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM prepare_fcat_disp .
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      i_structure_name       = 'ZSBTL_ABREPORT_ALV'
    CHANGING
      ct_fieldcat            = gt_fcat
    EXCEPTIONS
      inconsistent_interface = 1
      program_error          = 2
      OTHERS                 = 3.
  IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.                    " PREPARE_FCAT_DISP
*&---------------------------------------------------------------------*
*&      Form  MODIFY_FIELD_CAT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM modify_field_cat .

  FIELD-SYMBOLS : <ls_fcat> TYPE lvc_s_fcat.

  LOOP AT gt_fcat ASSIGNING <ls_fcat>.

    CASE <ls_fcat>-fieldname.
      WHEN 'MONTH1'.
        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH2'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH3'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH4'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH5'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH6'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MONTH7'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.
      WHEN 'MONTH8'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.
      WHEN 'MONTH9'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.
      WHEN 'MONTH10'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.
      WHEN 'MONTH11'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.
      WHEN 'MONTH12'.
        CALL FUNCTION 'HRAR_SUBTRACT_MONTH_TO_DATE'
          EXPORTING
            date                 = sy-datum
          IMPORTING
            date_minus_one_month = sy-datum.

        CASE sy-datum+4(02).
          WHEN 01.
            <ls_fcat>-scrtext_l =  'Jan Consume'.
            <ls_fcat>-scrtext_m =  'Jan Consume'.
            <ls_fcat>-scrtext_s =  'Jan Cons'.
          WHEN 02.
            <ls_fcat>-scrtext_l =  'Feb Consume'.
            <ls_fcat>-scrtext_m =  'Feb Consume'.
            <ls_fcat>-scrtext_s =  'Feb Cons'.
          WHEN 03.
            <ls_fcat>-scrtext_l =  'Mar Consume'.
            <ls_fcat>-scrtext_m =  'Mar Consume'.
            <ls_fcat>-scrtext_s =  'Mar Cons'.
          WHEN 04.
            <ls_fcat>-scrtext_l =  'Apr Consume'.
            <ls_fcat>-scrtext_m =  'Apr Consume'.
            <ls_fcat>-scrtext_s =  'Apr Cons'.
          WHEN 05.
            <ls_fcat>-scrtext_l =  'May Consume'.
            <ls_fcat>-scrtext_m =  'May Consume'.
            <ls_fcat>-scrtext_s =  'May Cons'.
          WHEN 06.
            <ls_fcat>-scrtext_l =  'Jun Consume'.
            <ls_fcat>-scrtext_m =  'Jun Consume'.
            <ls_fcat>-scrtext_s =  'Jun Cons'.
          WHEN 07.
            <ls_fcat>-scrtext_l =  'Jul Consume'.
            <ls_fcat>-scrtext_m =  'Jul Consume'.
            <ls_fcat>-scrtext_s =  'Jul Cons'.
          WHEN 08.
            <ls_fcat>-scrtext_l =  'Aug Consume'.
            <ls_fcat>-scrtext_m =  'Aug Consume'.
            <ls_fcat>-scrtext_s =  'Aug Cons'.
          WHEN 09.
            <ls_fcat>-scrtext_l =  'Sep Consume'.
            <ls_fcat>-scrtext_m =  'Sep Consume'.
            <ls_fcat>-scrtext_s =  'Sep Cons'.
          WHEN 10.
            <ls_fcat>-scrtext_l =  'Oct Consume'.
            <ls_fcat>-scrtext_m =  'Oct Consume'.
            <ls_fcat>-scrtext_s =  'Oct Cons'.
          WHEN 11.
            <ls_fcat>-scrtext_l =  'Nov Consume'.
            <ls_fcat>-scrtext_m =  'Nov Consume'.
            <ls_fcat>-scrtext_s =  'Nov Cons'.
          WHEN 12.
            <ls_fcat>-scrtext_l =  'Dec Consume'.
            <ls_fcat>-scrtext_m =  'Dec Consume'.
            <ls_fcat>-scrtext_s =  'Dec Cons'.
        ENDCASE.

      WHEN 'MIN_ROP'.
        <ls_fcat>-scrtext_l =  'Min. ROP'.
        <ls_fcat>-scrtext_m =  'Min. ROP'.
        <ls_fcat>-scrtext_s =  'Min. ROP'.
        <ls_fcat>-reptext   =  'Minimum ROP'.
      WHEN 'MATNR'.
        <ls_fcat>-hotspot =  'X'.
        <ls_fcat>-fix_column = 'X'.
      WHEN 'ATP'.
        <ls_fcat>-hotspot = 'X'.
* Begin of change DEVK909484
      WHEN 'XFR_QTY'.
        <ls_fcat>-scrtext_l =  'XFR Qty'.
        <ls_fcat>-scrtext_m =  'XFR Qty'.
        <ls_fcat>-scrtext_s =  'XFR Qty'.
        <ls_fcat>-reptext   =  'XFR Qty'.
* Begin of change DEVK909498
        <ls_fcat>-edit      = 'X'.                          "DEVK909502
* End   of change DEVK909498

      WHEN 'WERKS'.
        <ls_fcat>-fix_column = 'X'.
      WHEN 'MAKTX'.
        <ls_fcat>-fix_column = 'X'.
* End   of chagne DEVK909484
    ENDCASE.
  ENDLOOP.

ENDFORM.                    " MODIFY_FIELD_CAT
*&---------------------------------------------------------------------*
*&      Form  STOCK_REQ
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM stock_req .
  DATA : lv_matnr1 LIKE mara-matnr.
* Subroutine to get the selected rows.
  PERFORM get_sel_rows.

* Begin of change DEVK909502
*IF NO ROWS ARE SELECTED, USE THE CURRENT ROW.
  IF gt_index[] IS INITIAL.
    CLEAR gs_index.
    gs_index-index = gs_row_id-index.
    APPEND gs_index TO gt_index.
    READ TABLE it_data  INTO wa_data INDEX gs_index-index.
    gv_index = gs_index-index.
  ENDIF.
* End   of change DEVK909502

  IF  gt_index[] IS INITIAL.
    MESSAGE 'Select at least one record' TYPE 'E'.
  ELSE.
    CLEAR : lv_matnr1.
    MOVE wa_data-matnr TO lv_matnr1.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        input  = lv_matnr1
      IMPORTING
        output = lv_matnr1.

    SET PARAMETER ID 'MAT' FIELD lv_matnr1." wa_final-matnr.
    SET PARAMETER ID 'WRK' FIELD wa_data-werks.
    CALL TRANSACTION 'MD04' AND SKIP FIRST SCREEN.   "To Display transaction MD04
  ENDIF.

ENDFORM.                    " STOCK_REQ
*&---------------------------------------------------------------------*
*&      Form  GET_SEL_ROWS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM get_sel_rows .
  REFRESH: gt_index, gt_row.
  CLEAR : gv_lines, gv_index.                               "DEVK909484

  CALL METHOD gv_grid->get_selected_rows
    IMPORTING
      et_index_rows = gt_index
      et_row_no     = gt_row.

  DESCRIBE TABLE gt_row LINES gv_lines.

  IF gv_lines GT 1.
    MESSAGE 'Select only one Record' TYPE 'I'.
  ELSE.
    CLEAR : gs_index,
            wa_data.
    READ TABLE gt_index INTO gs_index INDEX 1 .
    READ TABLE it_data  INTO wa_data INDEX gs_index-index.
    gv_index = gs_index-index.                              "DEVK909484
  ENDIF.

ENDFORM.                    " GET_SEL_ROWS
*&---------------------------------------------------------------------*
*&      Form  CALL_BRANCH_TRANSFER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM call_branch_transfer .

  DATA : lv_matnr1 LIKE mara-matnr.

* Subroutine to get the selected rows.
  PERFORM get_sel_rows.

* Begin of change DEVK909502
*IF NO ROWS ARE SELECTED, USE THE CURRENT ROW.
  IF gt_index[] IS INITIAL.
    CLEAR gs_index.
    gs_index-index = gs_row_id-index.
    APPEND gs_index TO gt_index.
    READ TABLE it_data  INTO wa_data INDEX gs_index-index.
    gv_index = gs_index-index.
  ENDIF.
* End  of change DEVK909502

  IF gt_index[] IS INITIAL.
    MESSAGE 'Select at least one record' TYPE 'E'.
  ELSE.
    CLEAR : lv_matnr1.
    MOVE wa_data-matnr TO lv_matnr1.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        input  = lv_matnr1
      IMPORTING
        output = lv_matnr1.

    SET PARAMETER ID 'MAT' FIELD lv_matnr1." wa_final-matnr.
    SET PARAMETER ID 'WRK' FIELD wa_data-werks.
    CALL TRANSACTION '/ITS/MM_BRANCH_TRANSMD04' AND SKIP FIRST SCREEN.

* Begin of change DEVK909484
    PERFORM update_xfrqty_in_it_data.
    PERFORM refresh_alv_grid.
* End   of change DEVK909484
  ENDIF.

ENDFORM.                    " CALL_BRANCH_TRANSFER
*&---------------------------------------------------------------------*
*&      Form  HANDLE_ALV_TOOLBAR
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_E_OBJECT  text
*----------------------------------------------------------------------*
FORM handle_alv_toolbar  USING p_e_object TYPE REF TO cl_alv_event_toolbar_set.

  DATA: ls_toolbar  TYPE stb_button.

* Begin of change DEVK909502
  DELETE p_e_object->mt_toolbar FROM 3 TO 5.
  DELETE p_e_object->mt_toolbar FROM 8 TO 12.
  DELETE p_e_object->mt_toolbar INDEX 24.
* End   of change DEVK909502

* Add a separator to the toolbar
  ls_toolbar-butn_type = 3.      "Separator
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 23.
  CLEAR ls_toolbar.

* Add Update button to the toolbar
  ls_toolbar-function  = '&SRL'.
  ls_toolbar-icon      = icon_icon_list.
  ls_toolbar-quickinfo = 'Stock/Req. List (Shift-F2)'(012).
  ls_toolbar-text      =  ' Stock/Req. List'(013).
  ls_toolbar-butn_type = 0.      "Standard Button
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 24.
  CLEAR ls_toolbar.

* Add a separator to the toolbar
  ls_toolbar-butn_type = 3.      "Separator
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 25.
  CLEAR ls_toolbar.

* Add a Log button to the toolbar
  ls_toolbar-function  = '&TRANS'.
  ls_toolbar-icon      = icon_transport_point.
  ls_toolbar-quickinfo = 'Branch Transfer (Shift-F8)'(014).
  ls_toolbar-text      =  ' Branch Transfer'(015).
  ls_toolbar-butn_type = 0.      "Standard Button
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 26.
  CLEAR ls_toolbar.

* Begin of change DEVK909484
* Add a separator to the toolbar
  ls_toolbar-butn_type = 3.      "Separator
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 27.
  CLEAR ls_toolbar.

* Add a Log button to the toolbar
  ls_toolbar-function  = '&DELETE'.
  ls_toolbar-icon      = icon_delete_row.
  ls_toolbar-quickinfo = 'Delete Row (Ctrl-F9)'(016).
  ls_toolbar-text      =  ' Delete'(017).
  ls_toolbar-butn_type = 0.      "Standard Button
  ls_toolbar-disabled  = space.
  INSERT ls_toolbar INTO p_e_object->mt_toolbar INDEX 28.
  CLEAR ls_toolbar.
* End   of change DEVK909484

ENDFORM.                    " HANDLE_ALV_TOOLBAR
*&---------------------------------------------------------------------*
*&      Form  HANDLE_USER_COMMAND
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_E_UCOMM  text
*----------------------------------------------------------------------*
FORM handle_user_command  USING p_ucomm TYPE sy-ucomm.

* Begin of change DEVK909502
* Find the current row and column.
  CALL METHOD gv_grid->get_current_cell
    IMPORTING
      es_col_id = gs_col_id
      es_row_id = gs_row_id.
* End  of change DEVK909502

  CASE p_ucomm.
    WHEN '&SRL'.
      PERFORM stock_req.
    WHEN '&TRANS'.
      FREE MEMORY ID 'ZABBRANCH'.                           "DEVK909484
      PERFORM call_branch_transfer.

* Begin of change DEVK909484
    WHEN '&DELETE'.
      PERFORM delete_row_selected.
      PERFORM refresh_alv_grid.
* End   of change DEVK909484
  ENDCASE.

ENDFORM.                    " HANDLE_USER_COMMAND
*&---------------------------------------------------------------------*
*&      Form  UPDATE_XFRQTY_IN_IT_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM update_xfrqty_in_it_data .

  DATA : ls_memory TYPE ty_memory,
         lv_xfrqty TYPE minbe.
  REFRESH : gt_memory.
  IMPORT gt_memory FROM MEMORY ID 'ZABBRANCH'.

  LOOP AT gt_memory INTO ls_memory.
    lv_xfrqty = lv_xfrqty + ls_memory-labst.
  ENDLOOP.

  wa_data-xfr_qty = wa_data-xfr_qty - lv_xfrqty.

* Begin of change DEVK909498
  IF wa_data-xfr_qty LT 0.
    wa_data-xfr_qty = 0.
  ENDIF.
* End   of change DEVK909498

  MODIFY it_data INDEX gv_index
                 FROM wa_data TRANSPORTING xfr_qty.

ENDFORM.                    " UPDATE_XFRQTY_IN_IT_DATA

*&---------------------------------------------------------------------*
*&      Form  REFRESH_ALV_GRID
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM refresh_alv_grid .
  IF cl_gui_alv_grid=>offline( ) IS INITIAL.
    IF NOT gv_grid IS INITIAL.
* Begin of change DEVK909502
      CALL METHOD gv_grid->refresh_table_display
        EXPORTING
          is_stable = gv_lvc_s_stbl
        EXCEPTIONS
          finished  = 1
          OTHERS    = 2.
* End   of change DEVK909502
    ENDIF.
  ENDIF.
ENDFORM.                    " REFRESH_ALV_GRID
*&---------------------------------------------------------------------*
*&      Form  DELETE_ROW_SELECTED
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM delete_row_selected .

  DATA : ls_index TYPE lvc_s_row.

  REFRESH: gt_index, gt_row.
  CLEAR : gv_lines.

  CALL METHOD gv_grid->get_selected_rows
    IMPORTING
      et_index_rows = gt_index
      et_row_no     = gt_row.

  DESCRIBE TABLE gt_row LINES gv_lines.

  IF gv_lines = 0.
    MESSAGE 'Please select atleast one record!' TYPE 'I'.
  ELSE.
    LOOP AT gt_index INTO ls_index.
      DELETE it_data INDEX ls_index-index.
    ENDLOOP.
  ENDIF.

ENDFORM.                    " DELETE_ROW_SELECTED
